quarkus.console.enabled=false

# Livello di log per il tuo servizio
quarkus.log.category."ai.chatbot".level=DEBUG

# =========================================
# Configurazione del provider da usare.
# Possibili valori:
#   - ollama
#   - langchain
# =========================================
chat.provider=ollama

# =========================================
# Configurazione del modello da usare con ChatService
# modelli installati localmente e supportati:
#   - llama3
#   - mistral
#   - deepseek-llm
#   - deepseek-coder
# =========================================
ollama.model=llama3

# =========================================
# Configurazione del REST Client verso Ollama
# =========================================

# ollama-api: nome simbolico del client, deve corrispondere al valore specificato in @RegisterRestClient(configKey = "ollama-api")
# mp-rest: prefisso riservato da Quarkus per le configurazioni MicroProfile REST Client
ollama-api/mp-rest/url=http://localhost:11434
# Indica lo URL base del server Ollama locale

# (opzionale) Tempo massimo per stabilire la connessione (in millisecondi)
# ollama-api/mp-rest/connectTimeout=10000

# (opzionale) Tempo massimo per leggere una risposta (in millisecondi)
# ollama-api/mp-rest/readTimeout=60000

# (opzionale) Livello di logging HTTP per questo client (valori: NONE, BASIC, HEADERS, FULL)
# ollama-api/mp-rest/logger.level=FULL
