quarkus.console.enabled=false

# abilita i log dei rest-client
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body=true
quarkus.rest-client.logging.enabled=true

# Livello di log per il tuo servizio
quarkus.log.category."ai.chatbot".level=DEBUG

# =========================================
# Configurazione del provider da usare.
# Possibili valori:
#   - ollama
#   - langchain_local
#   - llamastack_local
# =========================================
chat.provider=ollama

# =========================================
# Configurazione del modello da usare con ChatService
# modelli installati localmente e supportati:
#   - llama3
#   - mistral
#   - deepseek-llm
#   - deepseek-coder
# =========================================
chat.model=llama3

# anche se questa property si riferisce a quella del RestClient e quindi ha lo stesso valore
# viene usata per inizializzare LangChain4J
chat.ollama.base-url=${ollama-api/mp-rest/url}

# =========================================
# Configurazione del REST Client verso Ollama
# =========================================

# ollama-api: nome simbolico del client, deve corrispondere al valore specificato in @RegisterRestClient(configKey = "ollama-api")
# mp-rest: prefisso riservato da Quarkus per le configurazioni MicroProfile REST Client
# Indica lo URL base del server Ollama locale
ollama-api/mp-rest/url=http://localhost:11434

# (opzionale) Tempo massimo per stabilire la connessione (in millisecondi)
# ollama-api/mp-rest/connectTimeout=10000

# (opzionale) Tempo massimo per leggere una risposta (in millisecondi)
# ollama-api/mp-rest/readTimeout=60000

# (opzionale) Livello di logging HTTP per questo client (valori: NONE, BASIC, HEADERS, FULL)
# ollama-api/mp-rest/logger.level=FULL

# =========================================
# Endpoint configurato da Podman AI Lab
# =========================================
llamastack-api/mp-rest/url=http://localhost:37625
