quarkus.console.enabled=false

# Livello di log per il tuo servizio
quarkus.log.category."ai.chatbot".level=DEBUG

# =========================================
# Configurazione del provider da usare.
# Possibili valori:
#   - ollama
#   - langchain_local
#   - prompt_routing_langchain_local
# =========================================
chat.provider=ollama

# =========================================
# Configurazione del modello da usare con ChatService
# modelli installati localmente e supportati:
#   - llama3
#   - llama3.2
#   - mistral
#   - deepseek-llm
#   - deepseek-coder
# =========================================
ollama.model=llama3.2

# anche se questa property si riferisce a quella del RestClient e quindi ha lo stesso valore
# viene usata per inizializzare LangChain4J
ollama.base-url=http://localhost:11434

# =========================================
# Configurazione del REST Client verso Ollama
# =========================================

# ollama-api: nome simbolico del client, deve corrispondere al valore specificato in @RegisterRestClient(configKey = "ollama-api")
# mp-rest: prefisso riservato da Quarkus per le configurazioni MicroProfile REST Client
# Indica lo URL base del server Ollama locale
ollama-api/mp-rest/url=${ollama.base-url}

# (opzionale) Tempo massimo per stabilire la connessione (in millisecondi)
# ollama-api/mp-rest/connectTimeout=10000

# (opzionale) Tempo massimo per leggere una risposta (in millisecondi)
# ollama-api/mp-rest/readTimeout=60000

# (opzionale) Livello di logging HTTP per questo client (valori: NONE, BASIC, HEADERS, FULL)
# ollama-api/mp-rest/logger.level=FULL


# =========================================
# Configurazione di LangChain4J per Quarkus
# =========================================
quarkus.langchain4j.ollama.devservices.enabled=false
quarkus.langchain4j.ollama.chat-model.model-id=${ollama.model}
quarkus.langchain4j.ollama.base-url=${ollama.base-url}
quarkus.langchain4j.ollama.timeout=300s
quarkus.langchain4j.log-requests=false
quarkus.langchain4j.log-responses=false